# Generated by Django 6.0.3 on 2026-03-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("purchase", "Выкуп"),
                            ("trade_in", "Trade-In"),
                            ("commission", "Реализация"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=200)),
                ("size", models.CharField(blank=True, max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Отличное"),
                            ("good", "Хорошее"),
                            ("satisfactory", "Удовлетворительное"),
                            ("parts", "На запчасти"),
                        ],
                        max_length=20,
                    ),
                ),
                ("defects_description", models.TextField(blank=True)),
                ("desired_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("offer_sent", "Предложение отправлено"),
                            ("accepted", "Принято"),
                            ("declined", "Отказано"),
                            ("contract_signed", "Договор подписан"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "offered_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="applications/%Y/%m/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото заявки",
                "verbose_name_plural": "Фото заявок",
                "db_table": "application_photos",
                "ordering": ["order"],
            },
        ),
    ]
