# Generated by Django 6.0.3 on 2026-03-10 17:32

import apps.offers.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=apps.offers.models.token_expiry),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
                "db_table": "offers",
            },
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=300)),
                ("date_of_birth", models.DateField()),
                ("passport_series", models.CharField(max_length=4)),
                ("passport_number", models.CharField(max_length=6)),
                ("passport_issued_by", models.CharField(max_length=500)),
                ("passport_issued_date", models.DateField()),
                ("registration_address", models.TextField()),
                ("inn", models.CharField(blank=True, max_length=12)),
                ("payment_details", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональные данные",
                "verbose_name_plural": "Персональные данные",
                "db_table": "personal_data",
            },
        ),
    ]
